# Generated by Django 5.2.15 on 2026-07-06 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=255, verbose_name='Varış Noktası Adı')),
                ('dest_latitude', models.FloatField(verbose_name='Hedef Enlem')),
                ('dest_longitude', models.FloatField(verbose_name='Hedef Boylam')),
                ('status', models.CharField(choices=[('PENDING', 'Başlatılmadı'), ('ACTIVE', 'Takip Ediliyor'), ('MUTED', 'Susturuldu / İptal Edildi'), ('ARRIVED', 'Varış Noktasına Ulaşıldı')], default='ACTIVE', max_length=15)),
                ('is_muted', models.BooleanField(default=False, verbose_name='Susturuldu mu?')),
                ('notified_1km', models.BooleanField(default=False)),
                ('notified_500m', models.BooleanField(default=False)),
                ('notified_250m', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
