# Generated by Django 5.2.15 on 2026-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetroute',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Cihaz Kimliği'),
        ),
    ]
