# Generated by Django 5.2.15 on 2026-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_targetroute_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetroute',
            name='user',
        ),
        migrations.AddField(
            model_name='targetroute',
            name='threshold_far_m',
            field=models.PositiveIntegerField(default=1000, verbose_name='Uzak Mesafe Eşiği (m)'),
        ),
        migrations.AddField(
            model_name='targetroute',
            name='threshold_mid_m',
            field=models.PositiveIntegerField(default=500, verbose_name='Orta Mesafe Eşiği (m)'),
        ),
        migrations.AddField(
            model_name='targetroute',
            name='threshold_near_m',
            field=models.PositiveIntegerField(default=250, verbose_name='Yakın Mesafe Eşiği (m)'),
        ),
    ]
